In [1]:
import numpy as np

In [7]:
a=np.arange(0, 24).reshape([-1, 3])

In [8]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [16]:
b=np.arange(24, 48).reshape([2, 3, 4])

In [4]:
import tensorflow as tf

In [13]:
with tf.Session() as sess:
    b=tf.reduce_sum(a, axis=1)
    print(sess.run(b))
    c=tf.reduce_mean(b)
    print(sess.run(c))
    print(sess.run(tf.reduce_mean(a)))

[ 3 12 21 30 39 48 57 66]
34
11


In [28]:
with tf.Session() as sess:
    c=tf.concat([a, b], axis=-1)
    print(sess.run(c))
    print(sess.run(tf.shape(c)))

[[[ 0  1  2  3 24 25 26 27]
  [ 4  5  6  7 28 29 30 31]
  [ 8  9 10 11 32 33 34 35]]

 [[12 13 14 15 36 37 38 39]
  [16 17 18 19 40 41 42 43]
  [20 21 22 23 44 45 46 47]]]
[2 3 8]


In [32]:
with tf.Session() as sess:
    c=tf.concat([a, b], axis=-1)
    print(sess.run(c))
    print(sess.run(tf.shape(c)))
    print(sess.run(tf.reshape(c, [-1, 24])))

[[[ 0  1  2  3 24 25 26 27]
  [ 4  5  6  7 28 29 30 31]
  [ 8  9 10 11 32 33 34 35]]

 [[12 13 14 15 36 37 38 39]
  [16 17 18 19 40 41 42 43]
  [20 21 22 23 44 45 46 47]]]
[2 3 8]
[[ 0  1  2  3 24 25 26 27  4  5  6  7 28 29 30 31  8  9 10 11 32 33 34 35]
 [12 13 14 15 36 37 38 39 16 17 18 19 40 41 42 43 20 21 22 23 44 45 46 47]]


In [11]:
l=['Adagrad', 'Adam', 'Ftrl', 'Momentum', 'RMSProp', 'SGD']
a='Ada'
if a not in l:
    raise ValueError('optimizer name must in:', ', '.join(str(p) for p in l))

ValueError: ('a must in:', 'Adagrad, Adam, Ftrl, Momentum, RMSProp, SGD')

In [2]:
a=[0, 1, 2, 3, 4, 5]

In [5]:
a[-5:]

[1, 2, 3, 4, 5]

In [8]:
import numpy as np
c = np.random.random([10,4])

In [9]:
c

array([[0.8865252 , 0.43584411, 0.56891338, 0.31299799],
       [0.32058895, 0.09466641, 0.55136498, 0.38011176],
       [0.87362878, 0.19643638, 0.60203029, 0.89104147],
       [0.04591807, 0.7605325 , 0.47349434, 0.27045576],
       [0.30200917, 0.63607701, 0.2713708 , 0.1196827 ],
       [0.82477742, 0.14769168, 0.48271175, 0.93773567],
       [0.63239771, 0.43670797, 0.77505197, 0.18157581],
       [0.29500087, 0.39819646, 0.35115378, 0.56916733],
       [0.47027824, 0.17974106, 0.90952103, 0.35159888],
       [0.87426793, 0.23066359, 0.94609097, 0.50498006]])

In [10]:
import tensorflow as tf
b = tf.nn.embedding_lookup(c, [1, 3])
 
with tf.Session() as sess:
    sess.run(tf.initialize_all_variables())
    print(sess.run(b))

Instructions for updating:
Use `tf.global_variables_initializer` instead.


[[0.32058895 0.09466641 0.55136498 0.38011176]
 [0.04591807 0.7605325  0.47349434 0.27045576]]


In [3]:
a=input("please input an integer:")

please input an integer:8


In [4]:
print(a)

8
